backend:
  name: github
  repo: Harjot1Singh/harjot.me
  squash_merges: true
  commit_messages:
    create: "feat(content): create {{slug}}"
    update: "feat(content): update {{slug}}"
    delete: |+
      feat(content): delete {{slug}}

      BREAKING CHANGE
    uploadMedia: "feat(media): upload {{path}}"
    deleteMedia: |+
      feat(media): delete {{path}}

      BREAKING CHANGE

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - {
          label: Related Projects,
          name: related-projects,
          required: false,
          widget: relation,
          collection: projects,
          valueField: title,
          searchFields: [title],
          multiple: true,
        }
      - { label: Body, name: body, widget: markdown }

  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: project-post,
        }
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Date, name: date, widget: datetime }
      - { label: Technologies, name: technologies, widget: list }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }

  - name: page-sections
    label: Page Sections
    files:
      - file: src/content/sections/home.md
        label: Home
        name: home-section
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: home-section,
            }
          - { label: Name, name: name, widget: string }
          - { label: Roles, name: roles, widget: list }
          - { label: Profile Picture, name: profilePicture, widget: image }
          - { label: CV, name: cv, widget: file }
          - {
              label: Icon Links,
              name: iconLinks,
              widget: list,
              fields:
                [
                  { label: URL, name: url, widget: string },
                  { label: Icon, name: icon, widget: image },
                ],
            }

      - file: src/content/sections/about.md
        label: About
        name: about-section
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: about-section,
            }
          - { label: Blurb, name: body, widget: markdown }
          - { label: Skills, name: skills, widget: list }

      - file: src/content/sections/projects.md
        label: Projects
        name: projects-section
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: projects-section,
            }
          - {
              label: Projects,
              name: projects,
              widget: relation,
              collection: projects,
              valueField: title,
              searchFields: [title],
              multiple: true,
            }

      - file: src/content/sections/contact.md
        label: Contact
        name: contact-section
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: contact-section,
            }
          - {
              label: Icon Links,
              name: iconLinks,
              widget: list,
              fields:
                [
                  { label: URL, name: url, widget: string },
                  { label: Icon, name: icon, widget: image },
                ],
            }
          - { label: Body, name: body, widget: markdown }
